# Generated by Django 4.0.4 on 2022-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0005_alter_post_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
